/**
 * PDF Export System - Generate clean formatted practice sheets
 */

import { jsPDF } from 'jspdf';

/**
 * Export practice sheet to PDF
 */
export function exportToPDF(state) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);

  let yPosition = margin;

  // Title
  doc.setFontSize(24);
  doc.setFont(undefined, 'bold');
  doc.text('Feynman Practice Sheet', margin, yPosition);

  yPosition += 10;

  // Concept
  doc.setFontSize(16);
  doc.setFont(undefined, 'normal');
  doc.text(state.concept || 'Unknown Concept', margin, yPosition);

  yPosition += 5;

  // Date
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Completed: ${new Date().toLocaleDateString()}`, margin, yPosition);

  yPosition += 15;

  // Divider line
  doc.setDrawColor(200);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);

  yPosition += 10;

  // Fields
  const fieldOrder = ['definition', 'mechanism', 'example', 'analogy', 'why_matters', 'misconception', 'integration'];

  fieldOrder.forEach((fieldName, index) => {
    const field = state.fields[fieldName];

    // Check if we need a new page
    if (yPosition > pageHeight - 60) {
      doc.addPage();
      yPosition = margin;
    }

    // Field title
    doc.setFontSize(14);
    doc.setFont(undefined, 'bold');
    doc.setTextColor(0);
    doc.text(formatFieldName(fieldName), margin, yPosition);

    yPosition += 7;

    // Field content
    doc.setFontSize(11);
    doc.setFont(undefined, 'normal');

    if (field.value && field.status === 'approved') {
      const lines = doc.splitTextToSize(field.value, maxWidth);
      doc.text(lines, margin, yPosition);
      yPosition += (lines.length * 6) + 5;
    } else {
      doc.setTextColor(150);
      doc.text('[Not completed]', margin, yPosition);
      doc.setTextColor(0);
      yPosition += 12;
    }

    // Spacing between fields
    yPosition += 5;

    // Light divider
    doc.setDrawColor(230);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 10;
  });

  // Footer - Review schedule
  if (yPosition > pageHeight - 80) {
    doc.addPage();
    yPosition = margin;
  }

  yPosition += 10;

  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text('Review Schedule', margin, yPosition);

  yPosition += 8;

  doc.setFontSize(10);
  doc.setFont(undefined, 'normal');

  const reviewSchedule = [
    '✓ Day 1: Review within 24 hours',
    '✓ Day 3: Review after 3 days',
    '✓ Day 7: Review after 1 week',
    '✓ Day 14: Review after 2 weeks',
    '✓ Day 30: Review after 1 month'
  ];

  reviewSchedule.forEach(item => {
    doc.text(item, margin + 5, yPosition);
    yPosition += 6;
  });

  yPosition += 10;

  // Attribution
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Feynman Learning System', margin, yPosition);

  // Save
  const filename = `feynman-${slugify(state.concept)}-${Date.now()}.pdf`;
  doc.save(filename);

  return filename;
}

/**
 * Format field name for display
 */
function formatFieldName(fieldName) {
  return fieldName
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}

/**
 * Create URL-safe slug from text
 */
function slugify(text) {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/--+/g, '-')
    .trim();
}

/**
 * Export continuation code as text file
 */
export function exportContinuationCode(code, concept) {
  const content = `Feynman Learning System - Continuation Code

Concept: ${concept}
Generated: ${new Date().toLocaleString()}

Continuation Code:
${code}

Instructions:
1. Copy the code above
2. Visit the Feynman Learning System
3. Use "Load Continuation Code" to resume your session

This code contains your complete learning progress and can be used to resume your session at any time.
`;

  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `feynman-continuation-${slugify(concept)}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
